modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "LGPL v3"

[[mods]]
modId = "healthindicators"
version = "${version}"
displayName = "Health Indicators"
authors = "AdyTech99"
description = '''
Simple damage indicator mod that shows a floating health bar (or number) above Players and Mobs.
'''
logoFile = "assets/healthindicators/icon.png"

[[dependencies.healthindicators]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthindicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthindicators]]
modId = "architectury"
type = "required"
versionRange = "[14.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "healthindicators.mixins.json"
