modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "LGPL v3"

[[mods]]
modId = "healthindicators"
version = "${version}"
displayName = "Health Indicators"
authors = "AdyTech99!"
description = '''
Health Bar!
'''
#logoFile = ""

[[dependencies.healthindicators]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthindicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.healthindicators]]
modId = "architectury"
type = "required"
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "healthindicators.mixins.json"
